version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --import-realm --hostname=localhost --hostname-strict=false
    environment:
      KC_BOOTSTRAP_ADMIN_USER: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_PROXY: ${KC_PROXY}
      KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT}
      KC_HOSTNAME_STRICT_HTTPS: ${KC_HOSTNAME_STRICT_HTTPS}
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - '8080:8080'
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./tmp:/opt/keycloak/data/import:ro
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '5173:5173'
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - VITE_KC_URL=http://localhost:8080
      - VITE_APP_URL=http://localhost:5173
    depends_on:
      - keycloak
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  keycloak_data: